// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUN6K6UuOWZd3jqQC3K5aDFX48InBUPI',
    appId: '1:981222704951:web:2dc8217b7127fa637dbcb2',
    messagingSenderId: '981222704951',
    projectId: 'sportcentrall-merch',
    authDomain: 'sportcentrall-merch.firebaseapp.com',
    storageBucket: 'sportcentrall-merch.appspot.com',
    measurementId: 'G-2XG6ZZTLQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUeb8dyk_9KRwbnQeVP8sVXqCVgLtV25Y',
    appId: '1:981222704951:android:594f7ec5e856aa967dbcb2',
    messagingSenderId: '981222704951',
    projectId: 'sportcentrall-merch',
    storageBucket: 'sportcentrall-merch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8wq3eO4w5k1uYFNqqmqNTJWCX44OUE_w',
    appId: '1:981222704951:ios:b1170f1f844b0a917dbcb2',
    messagingSenderId: '981222704951',
    projectId: 'sportcentrall-merch',
    storageBucket: 'sportcentrall-merch.appspot.com',
    iosClientId:
        '981222704951-v4bir3nva020ap2pevem6rhbguteakdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.merch',
  );
}
